SELECT      
 USERNAME,
 OPNAME, 
 TARGET, 
 ROUND((SOFAR/TOTALWORK),4)*100        		PERCENTAGE_COMPLETE, 
 START_TIME, 
 CEIL(TIME_REMAINING/60)                 	MAX_TIME_REMAINING_IN_MIN, 
 FLOOR(ELAPSED_SECONDS/60)                 	TIME_SPENT_IN_MIN 
FROM        V$SESSION_LONGOPS                       S
WHERE
 S.TIME_REMAINING > 0
;