WITH TMP1 AS
    (
    SELECT N, P, LEVEL AS LVL 
    FROM BST 
    START WITH P IS NULL 
    CONNECT BY PRIOR N = P 
    ORDER BY LEVEL
    )
SELECT
 TMP1.N,
 CASE
 WHEN TMP1.LVL = (SELECT MAX(TMP1.LVL) FROM TMP1) THEN 'Leaf' 
 WHEN TMP1.LVL = (SELECT MIN(TMP1.LVL) FROM TMP1) THEN 'Root' 
 ELSE 'Inner' 
 END
FROM TMP1
ORDER BY
 TMP1.N
;